In [1]:
import numpy as np

In [13]:
a = np.array([1,2,3,4,5])
b = np.array([.5, -1, 7.0, 8.9])

# Accessing Index Positions

In [17]:
b[0], b[2], b[-1]

(0.5, 7.0, 8.9)

In [18]:
b[[0, 2, -1]]

array([0.5, 7. , 8.9])

# Types

In [19]:
a.dtype

dtype('int64')

In [21]:
b.dtype

dtype('float64')

In [26]:
c = np.array([1.4, 5, 7.8, -1, 10.4], dtype=np.int8)
c

array([ 1,  5,  7, -1, 10], dtype=int8)

In [30]:
d = np.array([1,7,4,6,8,9,12, -6], dtype=float)
d

array([ 1.,  7.,  4.,  6.,  8.,  9., 12., -6.])

# Dimensions

In [32]:
e = np.array([
    [1,2,3],
    [9,8,7]
])
e

array([[1, 2, 3],
       [9, 8, 7]])

In [33]:
e.shape

(2, 3)

In [34]:
e.ndim

2

In [35]:
e.size

6

In [37]:
f = np.array([
    [[1,2,3],
    [4,5,6]]
    ,
    [[9,8,7],
    [6,5,4]]
])
f

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]]])

In [38]:
f.shape

(2, 2, 3)

In [39]:
f.ndim

3

In [40]:
f.size

12

# The Matrix

In [42]:
neo = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
neo

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
neo.shape

(3, 3)

In [45]:
neo.ndim

2

In [46]:
neo.size

9

In [47]:
neo[0]

array([1, 2, 3])

In [62]:
neo[0, 0]

1

In [63]:
neo[-1, -1]

9

In [64]:
neo[2, 1]

8

In [52]:
neo[1] = [10,11,12]
neo

array([[ 1,  2,  3],
       [10, 11, 12],
       [ 7,  8,  9]])

In [54]:
neo[1] = 4
neo

array([[1, 2, 3],
       [4, 4, 4],
       [7, 8, 9]])

In [55]:
neo[1] = np.array([4,5,6])
neo

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
neo[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
neo[:2][-1]

array([4, 5, 6])

In [67]:
neo[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Statistics

In [70]:
stats = np.array([1,2,3,4,5])
stats

array([1, 2, 3, 4, 5])

In [72]:
stats.sum()

15

In [73]:
stats.mean()

3.0

In [74]:
stats.std()

1.4142135623730951

In [75]:
stats.var()

2.0

In [77]:
stats2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
stats2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
stats2.sum(axis=0) #sum of the columns

array([12, 15, 18])

In [81]:
stats2.sum(axis=1) #sum of the rows

array([ 6, 15, 24])

# Broadcasting/Vectorized Operations

In [83]:
p = np.arange(10)
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
p * 2
p

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [88]:
p += 1
p

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [89]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [93]:
c = a + b
c

array([5, 7, 9])